version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=loginauth
      - DB_USER=/run/secrets/db_user
      - DB_PASSWORD=/run/secrets/db_password
      - EMAIL_HOST=smtp.example.com
      - EMAIL_PORT=587
      - EMAIL_USER=/run/secrets/email_user
      - EMAIL_PASSWORD=/run/secrets/email_password
      - EMAIL_FROM=sender@example.com
    secrets:
      - db_user
      - db_password
      - email_user
      - email_password

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=loginauth
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password

volumes:
  postgres_data:

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt
  email_user:
    file: ./secrets/email_user.txt
  email_password:
    file: ./secrets/email_password.txt
